---
apiVersion: v1
kind: Service
metadata:
  name: kavita
  labels:
    app: kavita
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
      name: http
  selector:
    app: kavita
