---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arrr
  labels:
    app: prowlarr
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
      nodePort: 30096
      name: http
  selector:
    app: prowlarr
