---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc
  namespace: arrr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
