---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
